---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
      - c528150a9c8526eaee904e9a01851d9b
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
      wrap-iife:
        enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - build/**/*
  - design/**/*
  - wire/**/*
  - app/js/vendor/**/*